/** @type {import('tailwindcss').Config} — ported from the user's Stitch design */
module.exports = {
  content: ["./src/renderer/index.html", "./src/renderer/src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e2dfff",
        "primary-fixed": "#dae1ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#390c00",
        "primary-fixed-dim": "#b3c5ff",
        "primary-container": "#0066ff",
        "surface-tint": "#0054d6",
        "on-error-container": "#93000a",
        "on-background": "#1b1b1c",
        "tertiary-fixed": "#ffdbd0",
        secondary: "#4c4aca",
        background: "#fcf9f8",
        "secondary-container": "#6664e4",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#832600",
        tertiary: "#a33200",
        "on-primary-fixed": "#001849",
        "inverse-surface": "#303030",
        "surface-container-high": "#eae7e7",
        primary: "#0050cb",
        "surface-dim": "#dcd9d9",
        "surface-container-highest": "#e5e2e1",
        "surface-bright": "#fcf9f8",
        "on-secondary-fixed": "#0c006a",
        "on-primary-fixed-variant": "#003fa4",
        surface: "#fcf9f8",
        "on-secondary-fixed-variant": "#3631b4",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-low": "#f6f3f2",
        "on-secondary": "#ffffff",
        outline: "#727687",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#fffbff",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#424656",
        "on-primary-container": "#f8f7ff",
        "outline-variant": "#c2c6d8",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#fff6f4",
        "secondary-fixed-dim": "#c2c1ff",
        "tertiary-fixed-dim": "#ffb59d",
        "surface-container": "#f0eded",
        "on-surface": "#1b1b1c",
        "tertiary-container": "#cc4204",
        "surface-variant": "#e5e2e1",
        "inverse-primary": "#b3c5ff",
        claude: "#5856D6",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        stack_sm: "8px",
        stack_md: "16px",
        stack_lg: "24px",
        margin_page: "24px",
        sidebar_width: "260px",
        gutter: "16px",
      },
      fontFamily: {
        "body-sm": ["Inter", "PingFang SC", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        headline: ["Inter", "PingFang SC", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
        display: ["Inter", "PingFang SC", "sans-serif"],
        "body-lg": ["Inter", "PingFang SC", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "700" }],
        headline: ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        code: ["13px", { lineHeight: "20px", fontWeight: "400" }],
        display: ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
};
